version: '3'
services:
  app:
    image: 'node:lts'
    working_dir: /app/
    command: npm run dev
    ports: 
      - "3000:3000"
    volumes:
        - ./:/app
  database:
    image: "postgres"
    ports:
      - "5432:5432"
    depends_on: 
      - app
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data: